### ISSUE TITLE
Tree shaking: Use es6-global strategy for modules

### ISSUE THREAD

**Issue by ashutheone** [porterin/reason-utils#24]
We can leverage benefits of tree-shaking by changing module bundling strategy to es6. As soon as all consumers support es6.

**Comment by porter473** [comment]
Tried comparing the bundle sizes for `frontend-website` with following combinations of package strategies and results were:
![image (3)](https://user-images.githubusercontent.com/59643407/105337385-5a51d580-5c00-11eb-8f2e-85c660762510.png)
Checked the sizes with `BundleAnalyzerPlugin` in staging environment, the sizes of the bundles generated in the 1st & 4th were identical, similarly for 2nd & 3rd case.
Thus it can be concluded that currently benefits depends on consumer’s bundling strategy.

**Comment by Prateek13727** [comment]
Fixed as Catalyst v2.0.2
